name: Trigger auto deployment for demo-cantainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-cantainer-AutoDeployTrigger-2429d9ad-45b3-40f4-8d50-3d91c73ab06f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOCANTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOCANTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOCANTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.DEMOCANTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOCANTAINER_REGISTRY_PASSWORD }}
          containerAppName: demo-cantainer
          resourceGroup: rg-cantainer-apps-southindia
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


